language: go

go:
  - "1.8" 
branches:
  only:
    - hugo 
install:
    - uname -a
    - wget https://github.com/gohugoio/hugo/releases/download/v0.55.4/hugo_0.55.4_Linux-64bit.deb
    - sudo dpkg -i hugo*.deb
    - hugo version
    - ls
    - pwd
script:
  - hugo
deploy:
  provider: pages
  skip-cleanup: true
  local-dir: public
  target-branch: master
  github-token: $GITHUB_TOKEN
  fqdn: a-cat.cn
  keep-history: true
  on:
    branch: hugo