language: go

install: go get -v github.com/gohugoio/hugo

script:
    - hugo
    
deploy:
    - cd ./public
    - git config user.name "ca7dEm0n"
    - git config user.email "a-ca7@139.com"
    - git init
    - git add .
    - git commit -m "# auto build"
    - git push --force "https://ca7dEm0n:${GITHUB_TOKEN}@${GITHUB_URL}" master:master

env:
    global:
        - GITHUB_URL: https://github.com/ca7dEm0n/docs.git    