baseURL = "https://a-cat.cn"
languageCode = "en-us"
title = "zeKe"
theme = "blank"

[taxonomies]
  tag = "tags"
  series = "series"
  category = "categories"

[highlighting] 
  pygmentsUseClassic       = true
  pygmentsCodeFences       = true
  pygmentsStyle            = "colorful"
